pub mod alter;
pub mod create_table;
pub mod do_block;
pub mod drop;
pub mod explain;
pub mod extension;
pub mod function;
pub mod index;
pub mod matview;
pub mod schema;
pub mod sequence;
#[cfg(not(target_arch = "wasm32"))]
pub mod subscription;
pub mod variable;
pub mod view;
